version: '3.4'

services:
  ticketr.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    networks:
      - "src_ticketr"

  ticketr.services.events:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
    networks:
      - "src_ticketr"

networks:
  src_ticketr:
